<template>
  <a-layout-content :style="{ margin: '24px 16px 0', overflow: 'initial' }">
    <div :style="{ padding: '24px', background: '#fff', textAlign: 'center' }">
      ...
      <br />Really
      <br />...
      <br />...
      <br />...
      <br />long
      <br />...
      <br />...
      <br />...
      <br />...
      <br />...
      <br />...
      <br />...
      <br />...
      <br />...
      <br />...
      <br />...
      <br />...
      <br />...
      <br />...
      <br />...
      <br />...
      <br />...
      <br />...
      <br />...
      <br />...
      <br />...
      <br />...
      <br />...
      <br />...
      <br />...
      <br />...
      <br />...
      <br />...
      <br />...
      <br />...
      <br />...
      <br />...
      <br />...
      <br />...
      <br />...
      <br />...
      <br />...
      <br />...
      <br />...
      <br />...
      <br />...
      <br />content
    </div>
  </a-layout-content>
</template>

<script lang='ts'>
import { ref, reactive, defineComponent } from "vue";

export default defineComponent({
  name: "Content",

  components: {},

  setup() {}
});
</script>

<style lang='scss' scoped>
</style>